spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
    server:7654
    
---
spring:
  profiles: prod
  application:
    name: springcloud-config-prod
    
#必须保存为UTF-8格式
      