spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:BrickCarrier666/springcloud-config.git
    
---
spring:
  profiles: prod
  application:
    name: springcloud-config-prod
    
#必须保存为UTF-8格式
      